In [1]:
range(5)

range(0, 5)

In [2]:
for i in range(5):
    print(i)

0
1
2
3
4


In [2]:
import numpy as np

In [3]:
a=  np.random.randn(5)

In [4]:
print(a)

[ 0.39296335 -1.32168149  0.04462175  0.41339974  0.76357217]


In [5]:
# assert(a.shape == (5,1))

In [6]:
#sigmoid function 

x = np.array([[1,2,3],

[4,5,6]])

In [7]:
print(1/(1+np.exp(-x)))

[[0.73105858 0.88079708 0.95257413]
 [0.98201379 0.99330715 0.99752738]]
